/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDonatableInterface extends ethers.utils.Interface {
  functions: {
    "donate(uint256,uint256,address,address,uint160,uint24)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "donate",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;

  events: {};
}

export class IDonatable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDonatableInterface;

  functions: {
    donate(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "donate(uint256,uint256,address,address,uint160,uint24)"(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  donate(
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    tokenIn: string,
    tokenOut: string,
    priceLimit: BigNumberish,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "donate(uint256,uint256,address,address,uint160,uint24)"(
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    tokenIn: string,
    tokenOut: string,
    priceLimit: BigNumberish,
    fee: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    donate(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "donate(uint256,uint256,address,address,uint160,uint24)"(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    donate(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "donate(uint256,uint256,address,address,uint160,uint24)"(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    donate(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "donate(uint256,uint256,address,address,uint160,uint24)"(
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      tokenIn: string,
      tokenOut: string,
      priceLimit: BigNumberish,
      fee: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
