name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://${{ secrets.PA }}@github.com/".insteadOf git+ssh://git@github.com
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
    - name: pnpm install
      run: pnpm install
    - name: build
      run: pnpm run nx run-many -- --target=build --all=true --with-deps=true
    - name: unit test
      run: pnpm run nx run-many -- --target=test --all=true --parallel=true 
    - name: e2e test
      run: pnpm run nx run-many -- --target=e2e --all=true